import { isStepActive, getActiveWorkflowModifications, TOOL_RECOMMENDATIONS } from './engine'

export function generateMarkdownSummary(config, spec, content) {
  const lines = []

  // Title
  lines.push('# Partner Program Workflow — Configuration Summary')
  lines.push('')
  lines.push(`Generated from the Partner Program Configurator`)
  lines.push('')

  // Configuration
  lines.push('## Your Configuration')
  lines.push('')
  lines.push(`- **Integration direction:** ${formatDP1(config.dp1)}`)
  lines.push(`- **Commercial motions:** ${formatDP2(config)}`)
  lines.push(`- **Certification:** ${formatDP3(config.dp3)}`)
  lines.push(`- **Regulated industries:** ${config.dp4 === 'yes' ? 'Yes — Compliance/Risk track active' : 'No'}`)
  lines.push('')

  // Active steps
  const stepKeys = Object.keys(spec.workflow_steps)
  const activeSteps = stepKeys.filter(k => isStepActive(k, config))
  const inactiveSteps = stepKeys.filter(k => !isStepActive(k, config))

  lines.push(`## Workflow Overview (${activeSteps.length} of ${stepKeys.length} steps active)`)
  lines.push('')

  for (const key of activeSteps) {
    const stepData = spec.workflow_steps[key]
    const stepNum = key.replace('step_', '')
    const stepContent = content[key] || {}

    lines.push(`### Step ${stepNum} — ${stepData.step_name}`)
    lines.push(`**Owner:** ${stepData.primary_owner || 'N/A'}`)
    lines.push('')

    // Purpose
    const purpose = (config.dp1 === 'no_integration' && stepContent.purpose_when_no_integration)
      ? stepContent.purpose_when_no_integration
      : stepContent.purpose
    if (purpose) {
      lines.push(`**Purpose:** ${purpose}`)
      lines.push('')
    }

    // Completion criteria
    const cc = stepData.completion_criteria
    if (cc) {
      const label = (config.dp1 === 'no_integration' && cc.done_label_when_no_integration)
        ? cc.done_label_when_no_integration
        : (cc.done_label || cc.note || '')
      if (label) {
        lines.push(`**Completion criteria:** ${label}`)
        lines.push('')
      }
    }

    // Configuration impact
    const mods = getActiveWorkflowModifications(key, stepData, spec, config)
    if (mods.length > 0) {
      lines.push('**How your configuration affects this step:**')
      for (const mod of mods) {
        lines.push(`- **${mod.label}:** ${mod.text}`)
      }
      lines.push('')
    }
  }

  // Inactive steps
  if (inactiveSteps.length > 0) {
    lines.push('## Inactive Steps')
    lines.push('')
    for (const key of inactiveSteps) {
      const stepData = spec.workflow_steps[key]
      const stepNum = key.replace('step_', '')
      lines.push(`- ~~Step ${stepNum} — ${stepData.step_name}~~ (skipped in this configuration)`)
    }
    lines.push('')
  }

  // Tool recommendations
  const activeTools = TOOL_RECOMMENDATIONS.filter(t => t.activeWhen(config))
  if (activeTools.length > 0) {
    lines.push('## Relevant Tools')
    lines.push('')
    for (const tool of activeTools) {
      lines.push(`**${tool.category}**${tool.description ? ` — ${tool.description}` : ''}`)
      lines.push(`Examples: ${tool.tools}`)
      lines.push('')
    }
  }

  // Footer
  lines.push('---')
  lines.push('')
  lines.push('Generated by the [Partner Program Configurator](https://nayanban.github.io/partner-program-configurator/)')
  lines.push(`Built by [Nayan B.](https://www.linkedin.com/in/banerjee-nayan/)`)

  return lines.join('\n')
}

function formatDP1(value) {
  const labels = {
    no_integration: 'No technical integration — purely commercial relationship',
    entity_to_partner: "Entity integrates into partner's system",
    partner_to_entity: "Partner integrates into entity's system",
    bidirectional: 'Bidirectional integration',
  }
  return labels[value] || value
}

function formatDP2(config) {
  const motions = config.dp2?.motions || []
  if (motions.length === 0) return 'None selected'
  const labels = {
    referral_inbound: 'Referral (inbound)',
    referral_outbound: 'Referral (outbound)',
    reseller_partner: 'Reseller (partner)',
    reseller_entity: 'Reseller (entity)',
    marketplace_entity: 'Marketplace (entity)',
    marketplace_partner: 'Marketplace (partner)',
    marketplace_third_party: 'Marketplace (third-party)',
    co_sell: `Co-sell (${config.dp2?.co_sell_direction || 'N/A'})`,
    co_marketing: `Co-marketing (${config.dp2?.co_marketing_funding || 'N/A'})`,
  }
  return motions.map(m => labels[m] || m).join(', ')
}

function formatDP3(value) {
  const labels = {
    neither: 'No certification required',
    integration_cert_only: 'Integration/technical certification only',
    partner_cert_only: 'Partner competency certification only',
    both: 'Both types of certification required',
  }
  return labels[value] || value
}
